require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PatientsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Patient. As you add validations to Patient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
      {first_name: [nil, "first_name"*4], last_name: [nil, "last_name"*4], status: [nil, "invalid"], location_id: nil, gender: "invalid", middle_name: "middle_name"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # Setup locations
  let(:locs){
        locations = []
        5.times.each{ locations.push create(:location) }
        locations
  }


  describe "GET #index" do
    it "assigns all patients as @patients" do
      arr = []
      5.times.each{ arr.push create(:patient) }
      get :index, {}
      expect(assigns(:patients)).to eq(arr)
    end

    it "renders the 'index' view" do
        get :index
        expect(response).to render_template :index
    end
  end

  describe "GET #show" do
    subject { create :patient }

    it "assigns the requested patient as @patient" do
      get :show, {:id => subject.to_param}
      expect(assigns(:patient)).to eq(subject)
    end

    it "render the 'show' view" do
      get :show, {:id => subject.to_param}
      expect(response).to render_template :show
    end
  end

  describe "GET #new" do
    it "assigns a new patient as @patient" do
      get :new, {}
      expect(assigns(:patient)).to be_a_new(Patient)
    end

    it "assign all locations as @locations" do
        get :new
        expect(assigns(:locations)).to eq(locs)
    end

    it "renders the 'new' view" do
        get :new
        expect(response).to render_template :new
    end
  end

  describe "GET #edit" do
    subject { create :patient }

    it "assigns the requested patient as @patient" do
      get :edit, {:id => subject.to_param}
      expect(assigns(:patient)).to eq(subject)
    end

    it "assigns all locations as @locations" do
        get :edit, { id: subject.to_param }
        expect(assigns(:locations)).to eq(locs)
    end

    it "renders the 'edit' view" do
        get :edit, {id: subject.to_param}
        expect(response).to render_template(:edit)
    end
  end

  describe "POST #create" do
    describe "with valid params" do
      it "creates a new Patient" do
        expect {
            post :create, {patient: attributes_for(:patient)}
        }.to change(Patient, :count).by(1)
      end

      it "assigns a newly created patient as @patient" do
        post :create, {:patient => attributes_for(:patient)}
        expect(assigns(:patient)).to be_a(Patient)
        expect(assigns(:patient)).to be_persisted
      end

      it "redirects to the created patient" do
        post :create, {:patient => attributes_for(:patient)}
        expect(response).to redirect_to(Patient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved patient as @patient" do
        post :create, {:patient => attributes_for(:patient, first_name: nil)}
        expect(assigns(:patient)).to be_a_new(Patient)
      end

      it "re-renders the 'new' template" do
        post :create, {:patient => attributes_for(:patient, first_name: nil)}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    let(:patient){
        create :patient
    }

    describe "with valid params" do
      let(:new_attributes) {
          attributes_for(:patient, first_name: "new_first_name")
      }

      it "updates the requested patient" do
        put :update, {:id => patient.to_param, :patient => new_attributes}
        patient.reload
        expect(patient.first_name).to eq("new_first_name")
      end

      it "assigns the requested patient as @patient" do
        put :update, {:id => patient.to_param, :patient => new_attributes}#}
        expect(assigns(:patient)).to eq(patient)
      end

      it "redirects to the patient" do
        put :update, {:id => patient.to_param, :patient => new_attributes}
        expect(response).to redirect_to(patient)
      end
    end

    describe "with invalid params" do
      it "assigns the patient as @patient" do
        put :update, {:id => patient.to_param, :patient => attributes_for(:patient, first_name: nil)}
        expect(assigns(:patient)).to eq(patient)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => patient.to_param, :patient => attributes_for(:patient, first_name: nil)}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    # before(:each) do
    #     patient = create(:patient)
    # end

    it "destroys the requested patient" do
      patient = create :patient
      expect {
        delete :destroy, {:id => patient.to_param}
      }.to change(Patient, :count).by(-1)
    end

    it "redirects to the patients list" do
      patient = create :patient
      delete :destroy, {:id => patient.to_param}
      expect(response).to redirect_to(patients_url)
    end
  end

end
